### ISSUE TITLE
consider social links

### ISSUE THREAD

**Issue by tipsy** [tipsy/github-profile-summary#41]
option to share profile on twitter and facebook?
include screencap of profile?

**Comment by tipsy** [comment]
![image](https://user-images.githubusercontent.com/1521451/34165514-c911500c-e4dc-11e7-9ada-ccfced87d4cb.png)

**Comment by tipsy** [comment]
position absolute, so the links don't follow the page when scrolling

**Comment by OrKoN** [comment]
It seems like Twitter blocks any tweets which lead to https://github-profile-summary.com/

**Comment by tipsy** [comment]
That's very strange.

**Comment by tipsy** [comment]
Has been fixed now @OrKoN

**Comment by 3642066** [comment]
Its nice, but maybe implementing Facebook SDK, its possible to pass variables to the share, its so simple.. Its also possible to make dynamic share image, could pass the github profile image to the open graph tags,   'piece of cake'... Facebook has updated api and i think could pass "25 public repos" and joined:  6 years ago, to the shares, using open graph, its a litle, .. complicated, for me, because i had spent too much time learning platform, but i can try to help on this .

**Comment by 3642066** [comment]
Could generate a image for the graphs. I did this sometime ago: Pass the image from profile, and pass another image, to mix both. Use a overlay for a second image, generated based on variables for :
Repos per Language
Stars per Language
Commits per Language
So, could share the result image, Github profile image and colored infos, i did it using PHP, takes huge processing from the server ,. but i had not saved the images on server, and i could upload that iimage on Facebook albuns, as i could share that as Facebook post, using fb feed, method share.. haha ..
It also used to publish the results at the Apps Page, so it had a lot of posts, i need update that .

I mean that; Implement sharing is basically everything to this project ;)
Also could make a kind of "iframe embedable" small version :)

**Comment by 3642066** [comment]
I could help on the code, but i never saw a code like yours before .. the final version code, is okay, i can understand... But i have no idea whats happening, on the sources, because its all weird :`P
